--Q1.Display employee name, department name, and salary.
select e.emp_name,d.dept_name,e.salary
from employees e join departments d
on e.dept_id = d.dept_id

--Q2.Show all departments and the number of employees in each department.
select d.dept_name,count(emp_id) as no_of_employees
from departments d left join employees e
on e.dept_id = d.dept_id
group by d.dept_name

--Q3.Find employees along with their manager names.
select e.emp_name as employee,m.emp_name as manager
from employees e join employees m
on e.manager_id = m.emp_id

--Q4.Find the total salary expenditure for each department.
select dept_id,sum(salary) as total_salary
from employees
group by dept_id

--Q5.Find the average salary for each department.
select dept_id,avg(salary) as avg_salary
from employees
group by dept_id

--Q6.Find the department with the highest average salary.
select dept_id,avg(salary) as avg_salary
from employees
group by dept_id
order by avg_salary desc limit 1

--Q7.Find employees earning more than the company average salary.
select emp_name,salary
from employees
where salary >(
  select avg(salary)
  from employees)
  
--Q8.Find employees earning more than their department average salary.
select e.emp_name,e.salary
from employees e
where salary >(
  	select avg(salary)
 	from employees
	group by dept_id = e.emp_id)

--Q9.Find the second highest salary in the company.
select max(salary)
from employees
where salary <
		(select max(salary)
		from employees)

--Q10.Find employees who earn the maximum salary in their department.
select emp_name, salary, dept_id
from employees e
where salary = (
    select MAX(salary)
    from employees
    where dept_id = e.dept_id)

--Q11.Rank employees based on salary within each department.
select emp_name,dept_id,salary,
	rank() over(partition by dept_id
            order by salary desc)
            as salary_rank
from employees

--Q12.Find the top 3 highest-paid employees in each department.
select *
from (
  select emp_name,dept_id,salary,
	rank() over(partition by dept_id
            order by salary desc)
            as salary_rank
	from employees
  ) t
where salary_rank <= 3

--Q13.Calculate running total salary ordered by hire date
select emp_name,hire_date,salary,
	sum(salary) over(order by hire_date,emp_id desc)
            as running_total_salary
from employees

--Q14.Show previous employee salary using LAG().
select emp_name,salary,
	lag(salary) over(order by emp_id)
            as prev_emp_salary
from employees

--Q15.Find customers who never placed an order.
select c.customer_id
from customers c left join orders o
on c.customer_id = o.customer_id
where order_id is NULL

--Q16.Find the latest order for each customer.
select customer_id,
       order_id,
       order_date
from (
    select customer_id,
           order_id,
           order_date,
           ROW_NUMBER() OVER (
               partition by customer_id
               order by order_date DESC
           ) as rn
    from orders
) t
where rn = 1;

--Q17.Find total sales generated by each customer.
select customer_id,sum(amount) 
from orders
group by customer_id

--Q18.Calculate customer contribution percentage to overall sales.
select customer_id,
       SUM(amount) as customer_sales,
       ROUND(
           SUM(amount) * 100.0 /
           SUM(SUM(amount)) OVER (),
           2
       ) as percentage
from orders
group by customer_id

--Q19.Identify duplicate customer names.
SELECT customer_name
FROM customers
GROUP BY customer_name
HAVING COUNT(*) > 1

--Q20.Classify employees into salary bands:
--Salary < 80,000        = Low
--80,000 - 120,000      = Medium
--Above 120,000         = High
--Display:
--Employee_Name
--Salary
--Salary_Band
select emp_name as employee_name,
       salary,
       CASE
           WHEN salary < 80000 THEN 'Low'
           WHEN salary <= 120000 THEN 'Medium'
           ELSE 'High'
       END as salary_band
from employees

--Q21.Find employees having the same salary.
select emp_name as employee_name,salary
from employees
where salary in (select salary
				from employees
                group by salary
                having count(*) >1)

--Q22.Find customers who placed more than 3 orders.
select customer_id ,count(order_id) as no_of_orders
from orders
group by customer_id
having no_of_orders > 3

--Q23.Find the month with highest sales.
select month(order_date),sum(amount) as sales
from orders
group by month(order_date)
order by sales  desc limit 1

--Q24.Calculate days between consecutive orders for each customer.
select customer_id,
       order_id,
       order_date,
       DATEDIFF(
           order_date,
           LAG(order_date) over (
               partition by customer_id
               order by order_date)
       ) as days_between_orders
from orders

--Q25.Find departments where no employee was hired in the last 2 years.
select d.dept_id,
       d.dept_name
from departments d
where d.dept_id not in (
    select distinct dept_id
    from employees
    where hire_date >= CURRENT_DATE - INTERVAL 2 YEAR
)
